## 1. List of Saving Dataset

In [1]:
import pandas as pd
from IPython.display import display

# Load dataset
df = pd.read_csv(r"C:\Users\WINDOWS 11\Desktop\year5\data for thesis\Data\List of Saving.csv")

# 1. First 5 rows
print("List of Saving")
display(df.head())

# 2. Data shape
print("\nDATA SHAPE")
print(df.shape)

# 3. Data Type + Unique Value Summary
print("\n DATA TYPE & UNIQUE VALUES ")

summary = pd.DataFrame({
    'Column Name': df.columns,
    'Data Type': df.dtypes.values,
    'Unique Values': df.nunique().values
})

display(summary)

List of Saving

,CID,SVACC,AccStatus,BalAmt,BranchCode,NextDisbDate,LnStatus,LnMatDate,LoanOustandingAmt,AmoutRequiredToClosed
0,BMC015433,BMC294000049040,A,20.50,BMC,16/12/2024,A,13/12/2027,"1,833.38","2,153.16"
1,BMC016544,BMC294000060585,D,0.41,BMC,NaN,NaN,NaN,NULL,NULL
2,BMC0007485,BMC294000064073,A,12.00,BMC,20/06/2025,A,08/06/2028,"1,166.64","1,569.84"
3,BMC010185,BMC294000066911,D,2.10,BMC,NaN,NaN,NaN,NULL,NULL
4,BMC0009406,BMC294000067576,A,672.63,BMC,20/03/2025,A,06/03/2029,"15,416.63","18,977.27"

DATA SHAPE
(4074, 10)

 DATA TYPE & UNIQUE VALUES

               Column Name Data Type  Unique Values
0                      CID    object           4074
1                    SVACC    object           4074
2                AccStatus    object              2
3                  BalAmt     object           1569
4               BranchCode    object             13
5             NextDisbDate    object            620
6                 LnStatus    object              1
7                LnMatDate    object            471
8       LoanOustandingAmt     object           1591
9   AmoutRequiredToClosed     object           2229

In [2]:

# Keep only necessary columns
df_saving = df[['CID', 'AccStatus']]

# Show result
print("=== FILTERED SAVING DATA ===")
display(df_saving.head())

# Check shape after reduction
print("\n=== NEW DATA SHAPE ===")
print(df_saving.shape)

=== FILTERED SAVING DATA ===

          CID AccStatus
0   BMC015433         A
1   BMC016544         D
2  BMC0007485         A
3   BMC010185         D
4  BMC0009406         A

=== NEW DATA SHAPE ===
(4074, 2)

## Loan Master Dataset

In [3]:
import pandas as pd
from IPython.display import display

# Load dataset
df = pd.read_csv(r"C:\Users\WINDOWS 11\Desktop\year5\data for thesis\Data\Loan Master Listing.csv")

# 1. First 5 rows
print("List of Saving")
display(df.head())

# 2. Data shape
print("\nDATA SHAPE")
print(df.shape)

# 3. Data Type + Unique Value Summary
print("\n DATA TYPE & UNIQUE VALUES ")

summary = pd.DataFrame({
    'Column Name': df.columns,
    'Data Type': df.dtypes.values,
    'Unique Values': df.nunique().values
})

display(summary)

List of Saving

,ACC,CID,PRINCIPALAMT,BALAMT,OverDuePri,OverDueInt,TERM_Extend,INTRATE,AcrIntAmt,LoanAge_Current,...,Principal_Fequency,Restructure,OrigTerm,GracePeriod,NumInstPaid,NumInstNotPaid,NumInstNotDue,Reloan,AgeOfReloan,PAYMENT_MODE
0,BMC892008137037,BMC008137,"1,600.00",754.74,132.42,52.96,72,18.0,56.88,166,...,1,N,72,0,38,6,28,Yes,46,Declining
1,BMC892009406033,BMC009406,"5,000.00","2,278.00","1,608.00",547,60,18.0,554.72,719,...,1,Y,36,3,26,24,10,Yes,0,Balloon
2,BMCLAFL20145501,BMC006164,"5,000.00",416.63,138.89,6.46,36,18.0,9.17,19,...,1,N,36,0,33,1,2,TOPUP,0,Declining
3,BMCLAFL20161896,BMC0032927,"4,000.00",777.81,-,-,36,18.0,5.07,0,...,1,N,36,0,29,0,7,No,0,Declining
4,BMCLAFL20178861,BMC010169,"4,000.00","2,113.75",891.5,210.17,36,18.0,217.66,257,...,1,N,36,0,16,9,11,No,0,Declining

DATA SHAPE
(4645, 25)

 DATA TYPE & UNIQUE VALUES

           Column Name Data Type  Unique Values
0                  ACC    object           4645
1                  CID    object           4617
2        PRINCIPALAMT     object            146
3              BALAMT     object           3172
4          OverDuePri     object           1556
5          OverDueInt     object           1562
6          TERM_Extend     int64             59
7              INTRATE   float64             13
8           AcrIntAmt     object           2559
9      LoanAge_Current     int64            274
10              PrType    object             25
11         AccountType    object              3
12              Sector    object              7
13           LOANCYCLE     int64             27
14         PARCategory    object              4
15  Principal_Fequency     int64             10
16         Restructure    object              3
17            OrigTerm     int64             42
18         GracePeriod     int64              8
19         NumInstPaid     int64             54
20      NumInstNotPaid     int64             36
21       NumInstNotDue     int64             83
22              Reloan    object              4
23         AgeOfReloan     int64            101
24        PAYMENT_MODE    object              3

Target / Label Variable(machine learning model is trained to predict)

In [4]:
def risk_level(par):
    if par == '0 days':
        return 1
    elif par == '1-29 days':
        return 2
    elif par == '30-89 days':
        return 3
    elif par == '90+ days':
        return 4
    else:
        return None

df['Risk_Level'] = df['PARCategory'].apply(risk_level)

In [5]:
from IPython.display import display
import pandas as pd

risk_counts = df['Risk_Level'].value_counts().sort_index()

In [6]:
label_mapping = {
    1: 'Normal',
    2: 'Slight Delay',
    3: 'Risk',
    4: 'High Risk'
}

table = pd.DataFrame({
    'Label': [label_mapping[i] for i in risk_counts.index],
    'Risk_Level': risk_counts.index,
    'Count': risk_counts.values
})

print("=== TABLE: LOAN RISK LEVEL COUNTS ===")
display(table)

=== TABLE: LOAN RISK LEVEL COUNTS ===

          Label  Risk_Level  Count
0        Normal           1   2864
1  Slight Delay           2    192
2          Risk           3    203
3     High Risk           4   1386

## Data Preprocessing 
1. Check missing value 
✅ STEP 1: Create Risk Label (Proxy Label — VERY IMPORTANT)

In [10]:
def risk_level(par):
    if par == '0 days':
        return 1
    elif par == '1-29 days':
        return 2
    elif par == '30-89 days':
        return 3
    elif par == '90+ days':
        return 4
    else:
        return None

df['Risk_Level'] = df['PARCategory'].apply(risk_level)

✅ STEP 2: Missing Values Check